POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RpdHVubnVzIiwiaWQiOiI2M2ExY2I4NWM2OGYxMjIzMGNlYWExMmMiLCJpYXQiOjE2NzE1NDc5MzZ9.PT23QQVTjgio-EaUtoIw6YeWc1fJScbNOdnyWLmSui4

{
    "title": "Toinen",
    "author": "asd",
    "url": "www.osoite.fi",
    "likes": "2"
}